#!/usr/bin/env python3
"""Audit the visual ground truth, and score the detector against it.

The `visual` block in every corpus — faces, QR codes, barcodes — has never
been checked, and it turns out not to be trustworthy: `documents/` annotates
two QR codes while the detector reports four, and nothing in the repository
says which side is wrong. Without a reliable count on the *input* there is no
precision or recall to report, only coverage against a number nobody audited.

So this reads each **original** image and asks a vision model what is
actually on the page. That gives three things the project did not have:

- a **proposed** visual annotation per image
- the detector's **recall** — real regions it found
- the detector's **precision** — regions it reported that are not there

**It reports; it does not rewrite.** What counts as PII is a policy question
for a person, and a ground truth generated by the same model that grades the
output is not independent. The proposal lands in `runs/visual_audit.json` for
a human to accept, and `datasets/*/annotations.json` is left alone.

Usage:
    python audit_visual.py                     # every corpus
    python audit_visual.py --corpus documents  # one
    python audit_visual.py --run runs/suite-1  # score detections from that run
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from rich.console import Console
from rich.table import Table

from redactor import datasets
from redactor.vision import DEFAULT_MODEL, build_client, encode_image

console = Console()
KINDS = ("face", "qr_code", "barcode")

PROMPT = """Look at this document image and count what is physically printed
on the page.

- **face**: photographs of a person's face. An ID portrait counts. A drawing,
  logo or silhouette does not.
- **qr_code**: square 2-D matrix codes with the three large finder squares in
  the corners. Only real QR codes — not a dense logo, watermark, guilloche
  pattern or block of small text.
- **barcode**: 1-D codes, parallel vertical bars of varying width. A MICR
  line of numerals along the bottom of a cheque is NOT a barcode.

This is an unredacted original, so nothing is covered. Count what is there,
and answer 0 where there is none. Be conservative: if you are unsure whether
a dense pattern is a real code, do not count it.
"""

SCHEMA = {
    "type": "object",
    "properties": {
        "face": {"type": "integer"},
        "qr_code": {"type": "integer"},
        "barcode": {"type": "integer"},
        "note": {"type": "string"},
    },
    "required": [*KINDS, "note"],
    "additionalProperties": False,
}


def read_page(client, model: str, path: Path) -> dict:
    response = client.messages.create(
        model=model,
        max_tokens=1024,
        thinking={"type": "adaptive"},
        output_config={"format": {"type": "json_schema", "schema": SCHEMA}},
        messages=[{"role": "user", "content": [
            encode_image(path), {"type": "text", "text": PROMPT},
        ]}],
    )
    if response.stop_reason == "refusal":
        raise RuntimeError(f"Refused: {getattr(response, 'stop_details', None)}")
    return json.loads(next(b.text for b in response.content if b.type == "text"))


def detections_for(run_dir: Path | None, corpus_name: str) -> dict[str, dict]:
    """What the detector reported, from a run's summary.json."""
    if run_dir is None:
        return {}
    for candidate in (run_dir / corpus_name / "summary.json", run_dir / "summary.json"):
        if candidate.exists():
            try:
                s = json.loads(candidate.read_text())
            except (OSError, json.JSONDecodeError):
                return {}
            return {r["filename"]: (r.get("visual_regions") or {}) for r in s["results"]}
    return {}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--corpus", action="append", default=None)
    parser.add_argument("--run", default=None,
                        help="Run folder whose detections to score, e.g. runs/suite-1")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--limit", type=int, default=None)
    args = parser.parse_args()

    client = build_client()
    run_dir = Path(args.run) if args.run else None
    names = args.corpus or [c for c in datasets.available() if c != "ktp"]

    proposal: dict[str, dict] = {}
    console.print("[dim]Reading originals. This proposes ground truth; it does "
                  "not write annotations.[/dim]\n")

    for corpus_name in names:
        try:
            corpus = datasets.load(corpus_name)
        except FileNotFoundError:
            continue
        detected = detections_for(run_dir, corpus_name)
        rows, stats = [], {k: {"tp": 0, "fp": 0, "fn": 0} for k in KINDS}
        items = list(corpus.items())[: args.limit] if args.limit else list(corpus.items())

        for name, path, entry in items:
            try:
                seen = read_page(client, args.model, path)
            except Exception as exc:
                console.print(f"[red]{corpus_name}/{name}: {exc}[/red]")
                continue
            truth = {k: int(seen.get(k, 0)) for k in KINDS}
            current = {k: int((entry.get("visual") or {}).get(k, 0)) for k in KINDS}
            got = {k: int(detected.get(name, {}).get(k, 0)) for k in KINDS}

            proposal.setdefault(corpus_name, {})[name] = {
                "proposed": truth, "current": current,
                "detected": got, "note": seen.get("note", ""),
            }
            for k in KINDS:
                stats[k]["tp"] += min(got[k], truth[k])
                stats[k]["fp"] += max(0, got[k] - truth[k])
                stats[k]["fn"] += max(0, truth[k] - got[k])
            if truth != current or (detected and got != truth):
                rows.append((name, current, truth, got))

        table = Table(title=f"{corpus_name} — disagreements")
        table.add_column("image", style="cyan")
        table.add_column("annotated now")
        table.add_column("vision says", style="bold")
        table.add_column("detector found")
        for name, cur, tru, got in rows:
            fmt = lambda d: ", ".join(f"{k}:{v}" for k, v in d.items() if v) or "—"
            table.add_row(name[:38], fmt(cur), fmt(tru), fmt(got) if detected else "n/a")
        console.print(table if rows else f"[green]{corpus_name}: no disagreements[/green]")

        if detected:
            pr = Table(title=f"{corpus_name} — detector vs proposed truth")
            pr.add_column("kind", style="cyan")
            pr.add_column("true positives", justify="right")
            pr.add_column("false positives", justify="right", style="yellow")
            pr.add_column("missed", justify="right", style="red")
            pr.add_column("precision", justify="right", style="bold")
            pr.add_column("recall", justify="right", style="bold")
            for k in KINDS:
                s = stats[k]
                if not any(s.values()):
                    continue
                p = s["tp"] / (s["tp"] + s["fp"]) if s["tp"] + s["fp"] else None
                r = s["tp"] / (s["tp"] + s["fn"]) if s["tp"] + s["fn"] else None
                pr.add_row(k, str(s["tp"]), str(s["fp"]), str(s["fn"]),
                           f"{p:.0%}" if p is not None else "—",
                           f"{r:.0%}" if r is not None else "—")
            console.print(pr)
        console.print()

    # Merged, not overwritten. `--corpus cheques` would otherwise drop the
    # documents and holdout proposals from the file, which is the same
    # destructive-overwrite bug vision_score.py had — written here within an
    # hour of fixing it there, which is why this comment exists.
    out = Path("runs") / "visual_audit.json"
    out.parent.mkdir(exist_ok=True)
    previous = {}
    if out.exists():
        try:
            previous = {
                k: v for k, v in json.loads(out.read_text()).items()
                if not k.startswith("_")
            }
        except (OSError, json.JSONDecodeError):
            previous = {}
    carried = [k for k in previous if k not in proposal]
    if carried:
        console.print(f"[cyan]carried over: {', '.join(sorted(carried))}[/cyan]")
    proposal = {**previous, **proposal}

    out.write_text(json.dumps({
        "_note": (
            "PROPOSED visual ground truth from audit_visual.py. Generated by a "
            "vision model reading the unredacted originals; not applied to any "
            "corpus. A person decides what counts before this is accepted, and "
            "it is not independent evidence — the same model family grades the "
            "redacted output."
        ),
        **proposal,
    }, indent=2))
    console.print(f"[green]Proposal written to[/green] {out}")
    console.print("[dim]Nothing in datasets/ was modified.[/dim]")


if __name__ == "__main__":
    main()
